version: "3"

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "3000:3000"
    command: sleep infinity
